# --------------------------------------------------------------
# GNUmakefile
# --------------------------------------------------------------

name := minidex_sim
G4TARGET := $(name)
G4EXLIB := true

G4DEBUG := 0

ROOTCFLAGS      = $(shell root-config --cflags)
ROOTLIBS        = $(shell root-config --libs)
ROOTGLIBS       = $(shell root-config --glibs)

EXTRALIBS +=$(ROOTLIBS)
EXTRALIBS +=$(ROOTGLIBS)
EXTRALIBS +=-L/Users/xliu/softwares/2.4.0.2/lib
EXTRALIBS +=-L/usr/lib
EXTRALIBS +=-L/Users/xliu/softwares/geant4.10.04.p01/lib


CPPFLAGS += $(ROOTCFLAGS)
CPPFLAGS += -Wl,-rpath,/Users/xliu/softwares/geant4.10.04.p01/lib

.PHONY: all
all: lib bin

include $(G4INSTALL)/config/binmake.gmk
